### ISSUE TITLE
Missing .gha file

### ISSUE THREAD

**Issue by DanielAbalde** [Tomalwo/FrOG#2]
Hi,
I can't find the file anywhere and I tried to clone the project in VS but:
1) I have GalapagosLibrary**.gha**, not GalapagosLibrary**.dll**, so I can't reference it in VS.
2) I'm also missing MetaheuristicsLibrary.dll.

I don't really need to compile it, I prefer the .gha, as I just want to try it out. But that's for your report.
So, could you send me the .gha or can I get it somehow? dga_3@hotmail.com

Thank you!

**Comment by Tomalwo** [comment]
Hi Dani,

FRoG.gha is attached, but its not very useful by itself.
It's main purpose is to help others to connect their optimization
algorithms to Grasshopper.

In regards to 1., you can just rename the *.gha to *.dll.

For 2., it's not strictly necessary, but you can get it here:
https://github.com/christophwaibel/FrOG
(Chris is collaborating with me on FroG, and will release a new
version of MetaheuristicsLibrary.dll
soon. Maybe ask him for it to motivate him ;-))

Hope that helps!

Cheers,
Thomas

**Comment by DanielAbalde** [comment]
I've cloned christophwaibel's repository and it's working fine.
I don't see any attachments but his repository contains the .gha file.
I have tried to change the name but it results in GalapagosLibrary.dll.gha. I've looked around a bit, and in the windows explorer view options you need the option to view the file extension checked. Then it works.

Thank you very much!
